spring.application.name=SpringBootEurekaClientApplication13
server.port=8081
server.servlet.context-path=/SpringBootEurekaClientApplication13
eureka.instance.instance-id=SpringBootEurekaClientApplication13
eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka